version: "3.7"
services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Transactions

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper:2888:3888

  kafka:
    image: confluentinc/cp-enterprise-kafka:latest
    hostname: kafka
    container_name: kafka
    depends_on: [zookeeper]
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9991
    ports:
      - 9092:9092     

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8080:80  # pgAdmin will be accessible at http://localhost:8080
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgres

  transaction:
    build:
      context: Transaction/
      dockerfile: ./Transaction.API/Dockerfile
    depends_on:
      - kafka
      - postgres
 
  antifraud:
    build:
      context: Transaction/
      dockerfile: ./AntiFraudService/Dockerfile
    depends_on:
      - kafka
      - transaction
    ports:
      - "8000:5000"